language: ruby
rvm:
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  exclude:
    - rvm: jruby-head
      jdk: openjdk6
  allow_failures:
    - rvm: jruby-head

notifications:
  email: false